backend:
name: git-gateway
branch: main

media_folder: "images"
public_folder: "/images"

collections:
- name: "articles"
label: "Articles"
folder: "articles"
create: true
slug: "{{slug}}"
fields:
- { label: "Title", name: "title", widget: "string" }
- { label: "Date", name: "date", widget: "datetime" }
- { label: "Body", name: "body", widget: "markdown" }
